language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

script: nosetests

install:
  - "pip install -r requirements.txt"
  - "pip install psycopg2"

notifications:
  email:
    - komissarex@gmail.com

services: postgresql
before_script:
  - psql -c 'create database test;' -U postgres
